title: Benjamin Pachter's Portfolio
email: ben.pachter@bellsouth.net
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benjaminpachter.com" # the base hostname & protocol for your site
theme: minima

# Build settings
markdown: kramdown

# Navigation links
header_pages:
  - index.markdown
  - about.markdown
  - resume.md
  - macro.md
  - micro.md
  - ETL.md
  - algos.md
